### ISSUE TITLE
在跑example的时候遇到core dump

### ISSUE THREAD

**Issue by yuan-luo** [hraftkv-project/hraftkv#1]
你好，我在跑example的时候遇到core dump。请问是什么原因？

另外，shflags文件找不到，我从braft原始repo中copy过来的。不知道对不对。

```
yuan@yuan-ubuntu18:~/hraftkv/example$ ll
total 44
drwxrwxr-x 3 yuan yuan  4096 May  9 17:05 ./
drwxrwxr-x 9 yuan yuan  4096 May  9 06:06 ../
drwxrwxr-x 6 yuan yuan  4096 May  9 17:09 hraftkv/
-rwxr-xr-x 1 yuan yuan 31149 May  9 17:05 shflags*

```

```
yuan@yuan-ubuntu18:~/hraftkv/example/hraftkv/build$ ./run_server.sh 
Using runtime_dir: ./runtime
I0509 17:16:32.453542 36183 /home/yuan/hraftkv/example/hraftkv/src/config.cpp:59] ConfigManager::_load_config: server config: server.ini client config: client.ini
I0509 17:16:32.453953 36183 /home/yuan/hraftkv/example/hraftkv/src/config.cpp:190] 
============== Config ==============
[server]
 - ip_addr: 172.31.22.0
 - port: 8100
 - index: 0
[raft]
 - data_path: ./runtime/data
 - stepdown_timeout_ms: 300
 - vote_timeout_ms: 300
[rocksdb]
 - dir: ./rocksdb
[KVStore_0]
 - start_key: 
 - end_key: 
 - conf: 192.168.10.26:8100:0,192.168.10.27:8100:0,192.168.10.28:8100:0
 - initial_priority: 5,4,4,4,4
 - initial_leader_priority: 5
 - election_timeout_ms: 100,150,150,150,150
[KVStore_1]
 - start_key: !
 - end_key: 3
 - conf: 192.168.10.26:8100:0,192.168.10.27:8100:0,192.168.10.28:8100:0
 - initial_priority: 5,4,4
 - initial_leader_priority: 5
 - election_timeout_ms: 100,150,150
[KVStore_2]
 - start_key: 3
 - end_key: 7
 - conf: 192.168.10.27:8100:0,192.168.10.28:8100:0,192.168.10.29:8100:0
 - initial_priority: 4,5,4
 - initial_leader_priority: 5
 - election_timeout_ms: 150,100,150
[KVStore_3]
 - start_key: 7
 - end_key: ~
 - conf: 192.168.10.28:8100:0,192.168.10.29:8100:0,192.168.10.30:8100:0
 - initial_priority: 4,4,5
 - initial_leader_priority: 5
 - election_timeout_ms: 150,150,100
============== Config ==============
I0509 17:16:32.454001 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:91] [INFO] ip_and_port=172.31.22.0:8100 ip_port_and_rep_idx=172.31.22.0:8100:0
I0509 17:16:32.454060 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:111] [Server] Multi-Raft mode enabled
I0509 17:16:32.454795 36183 /home/yuan/hraftkv/example/hraftkv/src/adapter/rocksdb_adapter.cpp:89] RocksDB::_start: recreate leveldb directory ./rocksdb
I0509 17:16:32.460196 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:130] [DEBUG] PeerId=172.31.22.0:8100:0, group_id=KVStore_0, node_idx=3, priority override: 0, election_timeout_ms=150
E0509 17:16:32.460248 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:180] conf_str=192.168.10.26:8100:0,192.168.10.27:8100:0,192.168.10.28:8100:0 does not contain server's peer_id=172.31.22.0:8100:0
E0509 17:16:32.460255 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:180] conf_str=192.168.10.27:8100:0,192.168.10.28:8100:0,192.168.10.29:8100:0 does not contain server's peer_id=172.31.22.0:8100:0
E0509 17:16:32.460258 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:180] conf_str=192.168.10.28:8100:0,192.168.10.29:8100:0,192.168.10.30:8100:0 does not contain server's peer_id=172.31.22.0:8100:0
E0509 17:16:32.464810 36183 src/brpc/server.cpp:956] Fail to listen 172.31.22.0:8100
E0509 17:16:32.464838 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:259] Fail to start Server
I0509 17:16:32.464843 36183 /home/yuan/hraftkv/example/hraftkv/src/server.cpp:287] KVStore service is going to quit
I0509 17:16:32.464849 36183 /home/yuan/hraftkv/src/braft/node.cpp:1055] node KVStore_0:172.31.22.0:8100:0 shutdown, current_term 0 state UNINITIALIZED
./run_server.sh: line 45: 36183 Segmentation fault      (core dumped) ${VALGRIND} ${PERF} ./kvstore_server -data_path=${data_dir} -raft_sync=${FLAGS_raft_sync} -raft_log_storage_type=${FLAGS_raft_log_storage_type}


yuan@yuan-ubuntu18:~/hraftkv/example/hraftkv/build/runtime$ gdb kvstore_server core
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kvstore_server...done.
[New LWP 35817]
[New LWP 35825]
[New LWP 35833]
[New LWP 35826]
[New LWP 35821]
[New LWP 35827]
[New LWP 35822]
[New LWP 35831]
[New LWP 35818]
[New LWP 35828]
[New LWP 35859]
[New LWP 35829]
[New LWP 35854]
[New LWP 35858]
[New LWP 35823]
[New LWP 35855]
[New LWP 35830]
[New LWP 35856]
[New LWP 35853]
[New LWP 35819]
[New LWP 35860]
[New LWP 35852]
[New LWP 35835]
[New LWP 35857]
[New LWP 35861]
[New LWP 35832]
[New LWP 35820]
[New LWP 35824]
[New LWP 35834]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./kvstore_server -data_path=./runtime/data -raft_sync=1 -raft_log_storage_type='.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005594632f34ea in braft::NodeImpl::shutdown (this=0x559466f90000, done=<optimized out>) at /home/yuan/hraftkv/src/braft/node.cpp:1082
1082	            if (_priority_manager->is_ple_enabled()) {
[Current thread is 1 (Thread 0x7fe9daac5cc0 (LWP 35817))]
(gdb) bt
#0  0x00005594632f34ea in braft::NodeImpl::shutdown (this=0x559466f90000, done=<optimized out>) at /home/yuan/hraftkv/src/braft/node.cpp:1082
#1  0x0000559463223c85 in hraftkv::Node::st (this=0x559466a630c0) at /home/yuan/hraftkv/example/hraftkv/src/node.h:85
#2  0x0000559463222555 in main (argc=1, argv=0x7ffe9500f510) at /home/yuan/hraftkv/example/hraftkv/src/server.cpp:291
(gdb) 

```

**Comment by hraftkv-project** [comment]
Hi Yuan,

Your server's ip "172.31.22.0" is not included in the cluster configuration "192.168.10.26:8100:0,192.168.10.27:8100:0,192.168.10.28:8100:0", so the server fail to start. 

The core dump appears because of this incorrect setting in the "config/server.ini" file. It does not affect the functionality of the program. 

The "shflags" file that we are using is the same as braft, so it should work properly. We will upload it back later, thanks for notifying us.

Thank you.
